/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AdminDash: typeof import('./src/components/Dashboards/AdminDash.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    BookOperation: typeof import('./src/components/BookOperation.vue')['default']
    BookPreview: typeof import('./src/components/BookPreview.vue')['default']
    BookSearch: typeof import('./src/components/BookSearch.vue')['default']
    BookTable: typeof import('./src/components/BookTable.vue')['default']
    HomeSlider: typeof import('./src/components/HomeSlider.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LogAddon: typeof import('./src/components/LogAddon.vue')['default']
    LogTable: typeof import('./src/components/LogTable.vue')['default']
    PayAddon: typeof import('./src/components/PayAddon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffDash: typeof import('./src/components/Dashboards/StaffDash.vue')['default']
    StateReciever: typeof import('./src/components/StateReciever.vue')['default']
    SuperDash: typeof import('./src/components/Dashboards/SuperDash.vue')['default']
    TypeList: typeof import('./src/components/TypeList.vue')['default']
    UserDash: typeof import('./src/components/Dashboards/UserDash.vue')['default']
    UserSearch: typeof import('./src/components/UserSearch.vue')['default']
    UserTable: typeof import('./src/components/UserTable.vue')['default']
  }
}
